// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: satd/events/v1/events.proto

package eventspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeEventStream_Subscribe_FullMethodName = "/satd.events.v1.NodeEventStream/Subscribe"
	NodeEventStream_Watch_FullMethodName     = "/satd.events.v1.NodeEventStream/Watch"
)

// NodeEventStreamClient is the client API for NodeEventStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeEventStreamClient interface {
	// Server-streaming firehose: the client opens one Subscribe call and
	// receives NodeEvent messages (category-filtered, optional durable
	// replay via from_cursor) until it disconnects. No client→server
	// messages on the stream.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NodeEvent], error)
	// Bidirectional watch stream: the client manages a live watch-set
	// (outpoints + scripts) via SubscribeControl messages and receives
	// OutpointSpent / ScriptMatched events the moment a watched outpoint is
	// spent or a watched script is paid (mempool + confirmed), interleaved
	// with the live category-filtered firehose. Each watch addition is
	// gated by the stream:watch capability and the per-token watch quota.
	Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeControl, NodeEvent], error)
}

type nodeEventStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeEventStreamClient(cc grpc.ClientConnInterface) NodeEventStreamClient {
	return &nodeEventStreamClient{cc}
}

func (c *nodeEventStreamClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NodeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeEventStream_ServiceDesc.Streams[0], NodeEventStream_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, NodeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeEventStream_SubscribeClient = grpc.ServerStreamingClient[NodeEvent]

func (c *nodeEventStreamClient) Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeControl, NodeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeEventStream_ServiceDesc.Streams[1], NodeEventStream_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeControl, NodeEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeEventStream_WatchClient = grpc.BidiStreamingClient[SubscribeControl, NodeEvent]

// NodeEventStreamServer is the server API for NodeEventStream service.
// All implementations must embed UnimplementedNodeEventStreamServer
// for forward compatibility.
type NodeEventStreamServer interface {
	// Server-streaming firehose: the client opens one Subscribe call and
	// receives NodeEvent messages (category-filtered, optional durable
	// replay via from_cursor) until it disconnects. No client→server
	// messages on the stream.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[NodeEvent]) error
	// Bidirectional watch stream: the client manages a live watch-set
	// (outpoints + scripts) via SubscribeControl messages and receives
	// OutpointSpent / ScriptMatched events the moment a watched outpoint is
	// spent or a watched script is paid (mempool + confirmed), interleaved
	// with the live category-filtered firehose. Each watch addition is
	// gated by the stream:watch capability and the per-token watch quota.
	Watch(grpc.BidiStreamingServer[SubscribeControl, NodeEvent]) error
	mustEmbedUnimplementedNodeEventStreamServer()
}

// UnimplementedNodeEventStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeEventStreamServer struct{}

func (UnimplementedNodeEventStreamServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[NodeEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedNodeEventStreamServer) Watch(grpc.BidiStreamingServer[SubscribeControl, NodeEvent]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedNodeEventStreamServer) mustEmbedUnimplementedNodeEventStreamServer() {}
func (UnimplementedNodeEventStreamServer) testEmbeddedByValue()                         {}

// UnsafeNodeEventStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeEventStreamServer will
// result in compilation errors.
type UnsafeNodeEventStreamServer interface {
	mustEmbedUnimplementedNodeEventStreamServer()
}

func RegisterNodeEventStreamServer(s grpc.ServiceRegistrar, srv NodeEventStreamServer) {
	// If the following call panics, it indicates UnimplementedNodeEventStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeEventStream_ServiceDesc, srv)
}

func _NodeEventStream_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeEventStreamServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, NodeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeEventStream_SubscribeServer = grpc.ServerStreamingServer[NodeEvent]

func _NodeEventStream_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeEventStreamServer).Watch(&grpc.GenericServerStream[SubscribeControl, NodeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeEventStream_WatchServer = grpc.BidiStreamingServer[SubscribeControl, NodeEvent]

// NodeEventStream_ServiceDesc is the grpc.ServiceDesc for NodeEventStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeEventStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "satd.events.v1.NodeEventStream",
	HandlerType: (*NodeEventStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _NodeEventStream_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _NodeEventStream_Watch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "satd/events/v1/events.proto",
}
