#!/usr/bin/env bash
#
# Run Bitcoin Core's functional tests against satd.
#
# Only the tests marked `status = "run"` in inventory.toml are executed, and
# they are named explicitly rather than excluded -- a test can never start
# running by accident because someone added a file upstream.
#
# Usage:
#   run.sh                 run the inventory's run-set
#   run.sh --list          print the run-set and exit
#   run.sh --dry-run       verify pin + inventory + binaries, run nothing
#   run.sh <test.py> ...   run specific tests (must be `run` in the inventory)
#   run.sh --candidate <test.py> ...
#                          run tests that are still `skip`, to find out whether
#                          a fix unblocks them. Not the scoreboard -- this is
#                          the measuring step of fix -> measure -> flip.
#   run.sh -- <args>       pass everything after -- to Core's test_runner.py
#
# Environment overrides (nothing here assumes a particular machine):
#   SATD_BIN       satd binary       (default: <repo>/target/release/satd)
#   SAT_CLI_BIN    sat-cli binary    (default: <repo>/target/release/sat-cli)
#   SATD_CORE_DIR  fetched Core tree (default: <script dir>/core)
#   SATD_CF_TMPDIR scratch dir for test datadirs (default: mktemp -d)
#   SATD_CF_JOBS   parallel jobs     (default: 1 -- see the note by JOBS below)

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
CORE_DIR="${SATD_CORE_DIR:-$HERE/core}"
# Core's framework resolves its config file and data files relative to the
# source root, so the fetched tree keeps Core's own layout.
FUNCTIONAL_DIR="$CORE_DIR/test/functional"
CONFIG_INI="$CORE_DIR/test/config.ini"

SATD_BIN="${SATD_BIN:-$REPO_ROOT/target/release/satd}"
SAT_CLI_BIN="${SAT_CLI_BIN:-$REPO_ROOT/target/release/sat-cli}"

MODE=run
CANDIDATE=0
EXPLICIT_TESTS=()
RUNNER_ARGS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --list)      MODE=list; shift ;;
        --dry-run)   MODE=dry;  shift ;;
        --candidate) CANDIDATE=1; shift ;;
        --)        shift; RUNNER_ARGS+=("$@"); break ;;
        -*)        RUNNER_ARGS+=("$1"); shift ;;
        *)         EXPLICIT_TESTS+=("$1"); shift ;;
    esac
done

# shellcheck source=/dev/null
source "$HERE/PIN"

die() { echo "error: $*" >&2; exit 1; }

# --- preflight ------------------------------------------------------------

[[ -d "$FUNCTIONAL_DIR" ]] || die "Core tree missing at $CORE_DIR -- run fetch-core.sh"

if [[ -f "$CORE_DIR/.satd-core-commit" ]]; then
    have="$(cat "$CORE_DIR/.satd-core-commit")"
    [[ "$have" == "$CORE_COMMIT" ]] ||
        die "Core tree is at $have but PIN says $CORE_COMMIT -- run fetch-core.sh --force"
else
    die "Core tree has no pin marker -- run fetch-core.sh --force"
fi

"$HERE/check_inventory.py" >/dev/null || die "inventory check failed"

mapfile -t RUN_SET < <("$HERE/check_inventory.py" --print-run-set)

if [[ $CANDIDATE -eq 1 ]]; then
    # Measuring, not scoring. A candidate run says whether a fix moved a
    # blocked test; only run.sh's default run-set is the scoreboard, and a
    # row still only flips to `run` in the PR that makes it pass.
    [[ ${#EXPLICIT_TESTS[@]} -gt 0 ]] || die "--candidate needs at least one test to measure"
    echo "--- candidate run: NOT the scoreboard, inventory status ignored ---" >&2
    RUN_SET=("${EXPLICIT_TESTS[@]}")
elif [[ ${#EXPLICIT_TESTS[@]} -gt 0 ]]; then
    for t in "${EXPLICIT_TESTS[@]}"; do
        found=0
        for r in ${RUN_SET[@]+"${RUN_SET[@]}"}; do [[ "$r" == "$t" ]] && found=1; done
        [[ $found -eq 1 ]] ||
            die "$t is not marked run in inventory.toml -- flip its row in the PR that makes it pass, or measure it with --candidate"
    done
    RUN_SET=("${EXPLICIT_TESTS[@]}")
fi

if [[ $MODE == list ]]; then
    printf '%s\n' ${RUN_SET[@]+"${RUN_SET[@]}"}
    exit 0
fi

[[ -x "$SATD_BIN" ]]    || die "satd not found at $SATD_BIN (build it, or set SATD_BIN)"
[[ -x "$SAT_CLI_BIN" ]] || die "sat-cli not found at $SAT_CLI_BIN (build it, or set SAT_CLI_BIN)"

# --- config.ini -----------------------------------------------------------
#
# Core's framework reads this to learn which components exist. Declaring a
# component false is how satd's real gaps reach the tests: the framework then
# raises its own SkipTest, so e.g. a wallet test reports "skipped" rather than
# failing on a missing RPC. That keeps the scoreboard honest in both directions
# -- we neither claim a pass we did not earn nor a failure we did not cause.

cat > "$CONFIG_INI" <<EOF
# Generated by run.sh -- do not edit, do not commit.
[environment]
CLIENT_NAME=satd
CLIENT_BUGREPORT=https://github.com/epochbtc/satd/issues
SRCDIR=$CORE_DIR
BUILDDIR=$CORE_DIR
EXEEXT=
RPCAUTH=$CORE_DIR/share/rpcauth/rpcauth.py

[components]
ENABLE_BITCOIND=true
ENABLE_CLI=true
# satd is walletless by design (the legacy Core wallet is out of scope).
ENABLE_WALLET=false
ENABLE_WALLET_TOOL=false
# satd's ZMQ carries the satd-events wire, not Core's hashblock/rawtx topics.
ENABLE_ZMQ=false
# Core-only build products and interfaces satd does not ship.
BUILD_BENCH=false
BUILD_BITCOIN_TX=false
ENABLE_BITCOIN_UTIL=false
ENABLE_BITCOIN_CHAINSTATE=false
ENABLE_FUZZ_BINARY=false
ENABLE_EMBEDDED_ASMAP=false
ENABLE_EXTERNAL_SIGNER=false
ENABLE_USDT_TRACEPOINTS=false
ENABLE_IPC=false
EOF

if [[ $MODE == dry ]]; then
    echo "pin:       $CORE_TAG ($CORE_COMMIT)"
    echo "satd:      $SATD_BIN"
    echo "sat-cli:   $SAT_CLI_BIN"
    echo "run-set:   ${#RUN_SET[@]} test(s)"
    echo "config:    $CONFIG_INI"
    echo "dry run -- nothing executed"
    exit 0
fi

if [[ ${#RUN_SET[@]} -eq 0 ]]; then
    echo "run-set is empty -- every inventory row is currently 'skip'."
    echo "That is the expected state until tests are flipped; nothing to do."
    exit 0
fi

# --- run ------------------------------------------------------------------

TMPDIR_BASE="${SATD_CF_TMPDIR:-$(mktemp -d -t satd-core-functional-XXXXXX)}"
mkdir -p "$TMPDIR_BASE"
# Serial by default, but no longer forced to be: the cached 199-block chain
# that test_runner seeds when jobs > 1 needs `setmocktime`, which satd now
# implements, and a full-suite run at 8 jobs produced no port collisions.
# Serial stays the default so a failure's logs are not interleaved with
# fifteen other tests'; raise SATD_CF_JOBS for a sweep.
JOBS="${SATD_CF_JOBS:-1}"
[[ "$JOBS" -lt 1 ]] && JOBS=1

export SATD_BIN SAT_CLI_BIN
export BITCOIND="$HERE/shims/bitcoind"
export BITCOINCLI="$HERE/shims/bitcoin-cli"

echo "Core $CORE_TAG vs satd -- ${#RUN_SET[@]} test(s), $JOBS job(s)"
echo "tmpdir: $TMPDIR_BASE"

RESULTS="$TMPDIR_BASE/results.csv"

set +e
python3 "$FUNCTIONAL_DIR/test_runner.py" \
    --configfile="$CONFIG_INI" \
    --tmpdir="$TMPDIR_BASE" \
    --cachedir="$TMPDIR_BASE/cache" \
    --jobs="$JOBS" \
    --resultsfile="$RESULTS" \
    ${RUNNER_ARGS[@]+"${RUNNER_ARGS[@]}"} \
    "${RUN_SET[@]}"
status=$?
set -e

# A green exit is not proof the run-set ran: Core's runner exits 0 for tests
# its own framework skipped at runtime. check_results.py holds the results to
# the inventory's claim.
if ! "$HERE/check_results.py" "$RESULTS" "${RUN_SET[@]}"; then
    status=1
fi

exit $status
