//! Subnet-level ban list with wall-clock times and JSON persistence.
//!
//! Bitcoin Core bans at the subnet level, stores ban entries as wall-clock
//! Unix timestamps (so they survive restarts and respond to `setmocktime`),
//! and persists the list to `banlist.json` in the chain data directory.
//!
//! The key type is a normalised address string — a CIDR subnet like
//! `"127.0.0.0/24"`, a bare IP normalised to `/32` or `/128`, or a `.onion`
//! hostname. SocketAddr ports are irrelevant: a ban on `127.0.0.1` bans
//! every port on that IP.

use ipnet::IpNet;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::net::IpAddr;
use std::path::{Path, PathBuf};

/// A single ban entry, in Bitcoin Core's `banlist.json` wire format.
///
/// Core's `CBanEntry::ToJson` (`src/net_types.cpp`) writes `version`,
/// `ban_created`, `banned_until` and `address`, and `BanMapFromJson` *drops*
/// -- rather than rejects -- an entry whose version it does not know. That is
/// what makes the field a forward-compatibility hinge rather than decoration,
/// so it is carried here too.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BanEntry {
    /// Core's `CBanEntry::CURRENT_VERSION`. Serialised first, as Core does.
    #[serde(default = "ban_entry_version")]
    pub version: i32,
    /// Normalised subnet string, e.g. `"127.0.0.0/24"`, `"<onion>"`.
    pub address: String,
    /// Unix seconds when the ban was created.
    pub ban_created: u64,
    /// Unix seconds when the ban expires.
    pub banned_until: u64,
}

/// Core's `CBanEntry::CURRENT_VERSION` (`src/net_types.h`).
pub const BAN_ENTRY_VERSION: i32 = 1;

fn ban_entry_version() -> i32 {
    BAN_ENTRY_VERSION
}

/// Core's on-disk shape: an object keyed by `banned_nets`, written through
/// `common::WriteSettings` alongside its `_warning_` note.
#[derive(Serialize, Deserialize)]
struct BanFile {
    #[serde(rename = "_warning_", default, skip_serializing_if = "Option::is_none")]
    warning: Option<String>,
    #[serde(default)]
    banned_nets: Vec<serde_json::Value>,
}

/// The note Core writes at the head of every settings-shaped file.
const BAN_FILE_WARNING: &str = "This file is automatically generated and updated by satd. \
Please do not edit this file while the node is running, as any changes might be ignored or \
overwritten.";

impl BanEntry {
    /// Original ban duration in seconds.
    pub fn ban_duration(&self) -> u64 {
        self.banned_until.saturating_sub(self.ban_created)
    }

    /// Seconds remaining until expiry, relative to `now` (Unix seconds).
    pub fn time_remaining(&self, now: u64) -> u64 {
        self.banned_until.saturating_sub(now)
    }

    /// Whether this ban has expired as of `now` (Unix seconds).
    pub fn is_expired(&self, now: u64) -> bool {
        now >= self.banned_until
    }
}

/// Read the `banned_nets` rows out of a `banlist.json`.
///
/// Core writes an object; satd used to write a bare array. Both are accepted
/// so an existing satd datadir does not lose its bans at the upgrade, and a
/// datadir Core has used is readable — which is the case that used to disable
/// persistence outright.
fn parse_ban_file(raw: &str) -> Result<Vec<serde_json::Value>, String> {
    let value: serde_json::Value =
        serde_json::from_str(raw).map_err(|e| format!("not valid JSON: {e}"))?;
    match value {
        serde_json::Value::Object(_) => serde_json::from_value::<BanFile>(value)
            .map(|f| f.banned_nets)
            .map_err(|e| format!("not a banlist object: {e}")),
        // satd's historical format.
        serde_json::Value::Array(rows) => Ok(rows),
        other => Err(format!("found non-object value {other}")),
    }
}

/// Core's `CBanEntry(const UniValue&)` plus `BanMapFromJson`'s two drop rules.
/// Returns `None` for a row that cannot be used.
///
/// Deliberately more lenient than Core in one direction: where Core *throws*
/// on a malformed field -- and `CBanDB::Read` catches that and discards the
/// whole file -- this drops the row and keeps the rest. Losing one unparseable
/// ban is strictly better than losing every ban because of it. A row with no
/// `version` at all is also kept, defaulted to the current version, which is
/// what lets satd's own historical array load; Core would throw on that too.
fn ban_entry_from_json(row: &serde_json::Value) -> Option<BanEntry> {
    let address = row.get("address")?.as_str()?.to_string();
    // Core drops an entry whose version it does not know, logging
    // "Dropping entry with unknown version". A row written by satd before
    // the field existed carries the current version by default -- it *was*
    // this version, it just did not say so.
    let version = match row.get("version") {
        None => BAN_ENTRY_VERSION,
        Some(v) => i32::try_from(v.as_i64()?).ok()?,
    };
    if version != BAN_ENTRY_VERSION {
        return None;
    }
    // "Dropping entry with unparseable address or subnet". The parse is also
    // what canonicalises the address: the result becomes the map key, and
    // `setban ... remove` looks up `BanTarget::normalised()`, so a row stored
    // under any other spelling is a ban that cannot be lifted.
    let address = parse_ban_target(&address).ok()?.normalised();
    Some(BanEntry {
        version,
        address,
        ban_created: row.get("ban_created")?.as_u64()?,
        banned_until: row.get("banned_until")?.as_u64()?,
    })
}

/// Clamp a Unix timestamp to what Bitcoin Core can parse back out of
/// `banlist.json`. See the call site for why an unclamped value is not merely
/// cosmetic.
fn clamp_for_core(secs: u64) -> u64 {
    secs.min(i64::MAX as u64)
}

/// Write `json` to `path` through a temporary file and a rename.
///
/// Core writes the file in place. satd does not, because its write happens on
/// the peer event loop at every automatic ban: an interrupted in-place write
/// leaves a truncated file, and a truncated banlist is one that fails to parse
/// on the next start. The rename is atomic on the same filesystem, so the
/// previous list survives a crash mid-write.
pub fn write_banlist(path: &Path, json: &str) -> std::io::Result<()> {
    let tmp = path.with_extension("json.tmp");
    std::fs::write(&tmp, json)?;
    if let Err(e) = std::fs::rename(&tmp, path) {
        // Do not leave a stale temporary next to the real file: the next
        // write would append nothing to it, but an operator inspecting the
        // datadir after a failure should not find a half-written banlist
        // sitting beside the good one.
        let _ = std::fs::remove_file(&tmp);
        return Err(e);
    }
    Ok(())
}

/// The parsed form of a `setban` subnet argument.
#[derive(Clone, Debug)]
pub enum BanTarget {
    /// An IPv4 or IPv6 subnet.
    Net(IpNet),
    /// A `.onion` hostname (verbatim, no CIDR).
    Onion(String),
}

impl BanTarget {
    /// The normalised string that becomes the map key and the `address`
    /// field in `banlist.json`.
    pub fn normalised(&self) -> String {
        match self {
            Self::Net(net) => net.trunc().to_string(),
            Self::Onion(s) => s.clone(),
        }
    }

    /// Whether `addr` falls within this ban target.
    pub fn contains_addr(&self, addr: &IpAddr) -> bool {
        match self {
            Self::Net(net) => net.contains(addr),
            Self::Onion(_) => false,
        }
    }
}

/// Parse a `setban` subnet argument into a `BanTarget`.
///
/// Accepts:
/// - Bare IPv4 (`"127.0.0.1"`) → `/32`
/// - Bare IPv6 (`"::1"`) → `/128`
/// - CIDR notation (`"127.0.0.0/24"`, `"2001:db8::/19"`)
/// - `.onion` hostnames (verbatim)
///
/// Returns `Err` with a human message on failure.
pub fn parse_ban_target(s: &str) -> Result<BanTarget, String> {
    // .onion addresses
    if s.ends_with(".onion") {
        return Ok(BanTarget::Onion(s.to_string()));
    }

    // Try CIDR first
    if let Ok(net) = s.parse::<IpNet>() {
        return Ok(BanTarget::Net(net));
    }

    // Try bare IP
    if let Ok(ip) = s.parse::<IpAddr>() {
        let net = IpNet::from(ip);
        return Ok(BanTarget::Net(net));
    }

    Err("Error: Invalid IP/Subnet".to_string())
}

/// The ban list: a map from normalised address string to ban entry.
///
/// `BTreeMap` gives sorted iteration, which Core's `listbanned` relies on
/// (the test asserts a specific order after restart).
#[derive(Clone, Debug, Default)]
pub struct BanList {
    entries: BTreeMap<String, BanEntry>,
    /// Path to `banlist.json`, set once at load time.
    persist_path: Option<PathBuf>,
    /// Core's `BanMan::m_is_dirty`: whether the in-memory list has changed
    /// since the last successful write. Persisting is deferred to
    /// [`BanList::take_pending_dump`] so the file I/O happens outside the
    /// lock, as Core's `DumpBanlist` does.
    dirty: bool,
}

impl BanList {
    /// Create an empty ban list that will persist to `path`.
    pub fn new(persist_path: PathBuf) -> Self {
        Self {
            entries: BTreeMap::new(),
            persist_path: Some(persist_path),
            dirty: true,
        }
    }

    /// Load from `banlist.json` at `path`, returning the list and whether the
    /// database had to be recreated (the caller logs Core's "Recreating the
    /// banlist database").
    ///
    /// **This never fails in a way that disables persistence.** Core's
    /// `BanMan::LoadBanlist` treats an unreadable or unparseable file exactly
    /// like a missing one: log, start from empty, mark dirty, carry on
    /// writing. satd used to return `Err` here, and the caller's response was
    /// to log a warning and leave the manager holding a `BanList::default()`
    /// -- whose `persist_path` is `None`, so every later `setban` was accepted
    /// by the RPC, applied in memory, and silently discarded on restart. A
    /// datadir Core had used was enough to trigger it, since the formats
    /// differed.
    ///
    /// Both formats are read: Core's `{"banned_nets": [...]}` object and the
    /// bare array satd used to write, so an existing satd datadir keeps its
    /// bans across the upgrade. Only Core's is written.
    pub fn load(path: &Path) -> (Self, bool, Option<String>) {
        let mut list = Self {
            entries: BTreeMap::new(),
            persist_path: Some(path.to_path_buf()),
            dirty: true,
        };

        if !path.exists() {
            return (list, true, None);
        }

        let raw = match std::fs::read_to_string(path) {
            Ok(raw) => raw,
            Err(e) => {
                return (
                    list,
                    true,
                    Some(format!("Cannot load banlist {}: {e}", path.display())),
                );
            }
        };

        let rows = match parse_ban_file(&raw) {
            Ok(rows) => rows,
            Err(e) => {
                return (
                    list,
                    true,
                    Some(format!("Cannot parse banlist {}: {e}", path.display())),
                );
            }
        };

        // Core's `BanMapFromJson` drops an individual bad row and keeps going;
        // it does not discard the file. An unknown `version` is the forward-
        // compatibility case, an unparseable address the corruption one.
        for row in rows {
            let Some(entry) = ban_entry_from_json(&row) else {
                continue;
            };
            list.entries.insert(entry.address.clone(), entry);
        }
        // `ban_entry_from_json` re-normalises the address, so the key it
        // inserts under is the same one `setban` computes. Keying on the
        // file's spelling instead made a non-canonical row unremovable:
        // `ipnet` does not mask host bits on construction (that is `trunc()`),
        // so `"10.0.0.5/8"` in the file matched `is_banned` but no `setban
        // ... remove` could ever name it -- `remove` looks up
        // `BanTarget::normalised()`, which is `"10.0.0.0/8"`. Core cannot
        // reach that state because its map key *is* the `CSubNet`, which
        // masks in its constructor.
        list.dirty = false;

        (list, false, None)
    }

    /// Whether the list has unwritten changes.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Core's `DumpBanlist` snapshot step: if there is anything to write,
    /// hand back the destination and the bytes and clear the dirty flag.
    ///
    /// Splitting the snapshot from the write is what keeps the file I/O off
    /// the lock. `dump()` used to run a blocking `fs::write` while holding the
    /// ban-list write lock, on the peer event loop.
    pub fn take_pending_dump(&mut self) -> Option<(PathBuf, String)> {
        if !self.dirty {
            return None;
        }
        let path = self.persist_path.clone()?;
        let file = BanFile {
            warning: Some(BAN_FILE_WARNING.to_string()),
            banned_nets: self
                .entries
                .values()
                .map(|e| serde_json::to_value(e).expect("BanEntry is serialisable"))
                .collect(),
        };
        let json = serde_json::to_string_pretty(&file).expect("BanFile is serialisable");
        self.dirty = false;
        Some((path, json))
    }

    /// Re-arm the dirty flag after a failed write, so the next flush retries.
    /// Core does the same in `DumpBanlist` when `m_ban_db.Write` fails.
    pub fn mark_dirty(&mut self) {
        self.dirty = true;
    }

    /// Insert a ban entry, or extend an existing one whose expiry is sooner.
    ///
    /// Core's `BanMan::Ban` is `if (m_banned[sub_net].nBanUntil < ban_entry
    /// .nBanUntil) m_banned[sub_net] = ban_entry;` — a missing key
    /// default-constructs with `nBanUntil = 0`, so a fresh ban always
    /// inserts and a repeat ban extends. Refusing a duplicate *here*
    /// instead broke the automatic path: `add_ban_score` discards the
    /// error, `prune_expired` does not run on a node that is not looking
    /// for peers, and so a peer whose ban had lapsed but whose entry was
    /// still in the map could misbehave forever without being re-banned,
    /// and sustained misbehaviour never extended an active ban.
    ///
    /// The operator-facing "already banned" refusal belongs to `setban`,
    /// which is where Core checks it — see [`BanList::already_banned`].
    pub fn add(
        &mut self,
        target: &BanTarget,
        ban_created: u64,
        banned_until: u64,
    ) -> Result<(), String> {
        let key = target.normalised();

        if self
            .entries
            .get(&key)
            .is_some_and(|e| e.banned_until >= banned_until)
        {
            return Ok(());
        }

        self.entries.insert(
            key.clone(),
            BanEntry {
                version: BAN_ENTRY_VERSION,
                address: key,
                ban_created: clamp_for_core(ban_created),
                // Core parses both timestamps with `getInt<int64_t>()`, which
                // *throws* above `INT64_MAX` -- and `CBanDB::Read` answers a
                // throw by discarding the entire ban list. satd's `setban`
                // takes a `u64` bantime and saturates, so an operator could
                // write a file that silently costs Core every one of its bans.
                // Core's own RPC cannot produce such a value (`banTime` is
                // `int64_t`), so clamping loses nothing real: the timestamp is
                // already ~292 billion years out.
                banned_until: clamp_for_core(banned_until),
            },
        );

        self.dirty = true;
        Ok(())
    }

    /// Core's `setban` duplicate check: expiry-aware, and sensitive to
    /// whether the operator wrote CIDR notation.
    ///
    /// `src/rpc/net.cpp` does `isSubnet ? IsBanned(subNet) : IsBanned(netAddr)`.
    /// A subnet argument therefore matches only an exact existing entry, while
    /// a bare IP also matches any subnet containing it — which is why banning
    /// `127.0.0.0/32` after `127.0.0.0/24` is allowed but banning the bare
    /// `127.0.0.0` is not. Both forms skip expired entries, so a ban that has
    /// lapsed never blocks a fresh one.
    pub fn already_banned(&self, target: &BanTarget, is_subnet: bool, now: u64) -> bool {
        let key = target.normalised();
        if self
            .entries
            .get(&key)
            .is_some_and(|e| !e.is_expired(now))
        {
            return true;
        }
        if is_subnet {
            return false;
        }
        match target {
            BanTarget::Net(net) => self.is_banned(&net.addr(), now),
            BanTarget::Onion(host) => self.is_onion_banned(host, now),
        }
    }

    /// Remove a ban entry by exact key match. Returns `Err` if no such
    /// entry exists.
    pub fn remove(&mut self, target: &BanTarget) -> Result<(), String> {
        let key = target.normalised();
        if self.entries.remove(&key).is_none() {
            return Err("Error: Unban failed. Requested address/subnet was not previously manually banned.".to_string());
        }
        self.dirty = true;
        Ok(())
    }

    /// Clear all bans.
    pub fn clear(&mut self) {
        self.entries.clear();
        self.dirty = true;
    }

    /// Remove expired entries, using `now` as the current time (Unix secs).
    pub fn prune_expired(&mut self, now: u64) {
        let before = self.entries.len();
        self.entries.retain(|_, e| !e.is_expired(now));
        if self.entries.len() != before {
            self.dirty = true;
        }
    }

    /// All non-expired entries, sorted by key.
    pub fn list(&self, now: u64) -> Vec<&BanEntry> {
        self.entries
            .values()
            .filter(|e| !e.is_expired(now))
            .collect()
    }

    /// Whether `addr` is currently banned (falls within any non-expired
    /// subnet), given `now` in Unix seconds.
    pub fn is_banned(&self, addr: &IpAddr, now: u64) -> bool {
        for entry in self.entries.values() {
            if entry.is_expired(now) {
                continue;
            }
            // .onion entries only match by exact key, never by IP.
            if entry.address.ends_with(".onion") {
                continue;
            }
            if let Ok(net) = entry.address.parse::<IpNet>()
                && net.contains(addr)
            {
                return true;
            }
        }
        false
    }

    /// Whether the given .onion hostname is currently banned.
    pub fn is_onion_banned(&self, host: &str, now: u64) -> bool {
        self.entries
            .get(host)
            .map(|e| !e.is_expired(now))
            .unwrap_or(false)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn parse_bare_ipv4() {
        let target = parse_ban_target("127.0.0.1").unwrap();
        assert_eq!(target.normalised(), "127.0.0.1/32");
    }

    #[test]
    fn parse_cidr_v4() {
        let target = parse_ban_target("127.0.0.0/24").unwrap();
        assert_eq!(target.normalised(), "127.0.0.0/24");
    }

    #[test]
    fn parse_onion() {
        let target = parse_ban_target(
            "pg6mmjiyjmcrsslvykfwnntlaru7p5svn6y2ymmju6nubxndf4pscryd.onion",
        )
        .unwrap();
        assert!(matches!(target, BanTarget::Onion(_)));
    }

    #[test]
    fn parse_ipv6_cidr() {
        let target =
            parse_ban_target("2001:4d48:ac57:400:cacf:e9ff:fe1d:9c63/19").unwrap();
        assert!(target.normalised().contains("/19"));
    }

    #[test]
    fn parse_invalid_cidr() {
        assert!(parse_ban_target("127.0.0.1/42").is_err());
    }

    #[test]
    fn subnet_contains_ip() {
        let target = parse_ban_target("127.0.0.0/24").unwrap();
        let ip: IpAddr = "127.0.0.1".parse().unwrap();
        assert!(target.contains_addr(&ip));
    }

    /// The duplicate refusal moved from `add` to the `setban` RPC, where Core
    /// checks it — `add` itself must always insert or extend, or the
    /// misbehaviour path can never re-arm an expired ban.
    #[test]
    fn already_banned_within_subnet() {
        let mut list = BanList::default();
        let subnet = parse_ban_target("127.0.0.0/24").unwrap();
        list.add(&subnet, 1000, 2000).unwrap();

        // A bare IP inside a banned subnet is a duplicate: Core's `setban`
        // takes the `IsBanned(netAddr)` branch, which scans for a containing
        // subnet.
        let ip = parse_ban_target("127.0.0.1").unwrap();
        assert!(list.already_banned(&ip, false, 1500));

        // Written as CIDR it is not: Core's `isSubnet` branch looks for an
        // exact entry only, which is why `127.0.0.1/32` after `127.0.0.0/24`
        // is allowed.
        let cidr = parse_ban_target("127.0.0.1/32").unwrap();
        assert!(!list.already_banned(&cidr, true, 1500));

        // Expiry is part of the question. Once the subnet ban has lapsed it
        // blocks nothing.
        assert!(!list.already_banned(&ip, false, 2001));

        // And `add` itself never refuses — it inserts, or extends a shorter
        // ban, so a re-ban after expiry always takes.
        assert!(list.add(&ip, 1000, 2000).is_ok());
        list.add(&ip, 3000, 9000).unwrap();
        assert!(list.is_banned(&"127.0.0.1".parse().unwrap(), 5000));
    }

    /// The file satd writes must be the file Core reads: an object keyed by
    /// `banned_nets`, entries carrying `version`.
    #[test]
    fn the_written_file_is_cores_shape() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("banlist.json");
        let mut list = BanList::new(path.clone());
        list.add(&parse_ban_target("127.0.0.0/24").unwrap(), 1000, 2000)
            .unwrap();

        let (dest, json) = list.take_pending_dump().expect("a dirty list has a dump");
        write_banlist(&dest, &json).unwrap();

        let v: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert!(v.is_object(), "Core writes an object, not a bare array");
        assert!(v.get("_warning_").is_some(), "Core's generated-file note");
        let rows = v["banned_nets"].as_array().expect("banned_nets array");
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0]["version"], json!(BAN_ENTRY_VERSION));
        assert_eq!(rows[0]["address"], json!("127.0.0.0/24"));
        assert_eq!(rows[0]["ban_created"], json!(1000));
        assert_eq!(rows[0]["banned_until"], json!(2000));

        // Nothing further to write until something changes.
        assert!(list.take_pending_dump().is_none());
        assert!(!path.with_extension("json.tmp").exists(), "no temp file left behind");
    }

    /// Core's format, satd's historical bare array, and a round trip.
    #[test]
    fn both_on_disk_formats_load() {
        let core_form = r#"{
          "_warning_": "…",
          "banned_nets": [
            {"version": 1, "address": "10.0.0.0/8", "ban_created": 1, "banned_until": 9999999999}
          ]
        }"#;
        let satd_legacy = r#"[
            {"address": "10.0.0.0/8", "ban_created": 1, "banned_until": 9999999999}
        ]"#;

        for (label, raw) in [("core", core_form), ("satd-legacy", satd_legacy)] {
            let dir = tempfile::tempdir().unwrap();
            let path = dir.path().join("banlist.json");
            std::fs::write(&path, raw).unwrap();
            let (list, recreated, why) = BanList::load(&path);
            assert!(!recreated, "{label}: a readable list is not recreated ({why:?})");
            assert!(why.is_none(), "{label}: {why:?}");
            assert_eq!(list.list(0).len(), 1, "{label}: the ban survived the load");
            assert!(
                list.is_banned(&"10.1.2.3".parse().unwrap(), 100),
                "{label}: and it still bans"
            );
        }
    }

    /// The consequence that made this more than a format difference: satd
    /// answered an unparseable file by dropping its persist path, so every
    /// later `setban` was accepted and silently discarded. Core recreates the
    /// database and carries on writing.
    #[test]
    fn an_unreadable_list_is_recreated_not_silently_disabled() {
        for junk in ["not json at all", "{\"banned_nets\": 7}", "42"] {
            let dir = tempfile::tempdir().unwrap();
            let path = dir.path().join("banlist.json");
            std::fs::write(&path, junk).unwrap();

            let (mut list, recreated, why) = BanList::load(&path);
            assert!(recreated, "{junk:?} must recreate the database");
            assert!(why.is_some(), "{junk:?} must say why");
            assert!(list.list(0).is_empty());

            // The critical part: a ban set after the failed load is written.
            list.add(&parse_ban_target("127.0.0.1").unwrap(), 1, 9999999999)
                .unwrap();
            let (dest, json) = list
                .take_pending_dump()
                .expect("persistence must survive a failed load");
            write_banlist(&dest, &json).unwrap();

            let (reloaded, _, _) = BanList::load(&path);
            assert_eq!(reloaded.list(0).len(), 1, "{junk:?}: the ban must survive a restart");
        }
    }

    /// Core's `BanMapFromJson` drops a bad row and keeps the rest, rather than
    /// discarding the file.
    #[test]
    fn a_bad_row_is_dropped_not_the_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("banlist.json");
        std::fs::write(
            &path,
            r#"{"banned_nets": [
                {"version": 99, "address": "10.0.0.0/8", "ban_created": 1, "banned_until": 9999999999},
                {"version": 1, "address": "not-an-address", "ban_created": 1, "banned_until": 9999999999},
                {"version": 1, "address": "192.168.0.0/16", "ban_created": 1, "banned_until": 9999999999}
            ]}"#,
        )
        .unwrap();

        let (list, recreated, _) = BanList::load(&path);
        assert!(!recreated);
        let kept: Vec<&str> = list.list(0).iter().map(|e| e.address.as_str()).collect();
        assert_eq!(kept, ["192.168.0.0/16"], "unknown version and bad address dropped");
    }

    /// A failed write must leave the previous list intact, not a truncated
    /// one — a truncated banlist is exactly the input that used to disable
    /// persistence on the next start.
    ///
    /// The failure is injected at the *temporary* file, which is what makes
    /// this test load-bearing: replace the body of `write_banlist` with a
    /// plain `fs::write(path, json)` and the write succeeds, `banlist.json`
    /// is clobbered, and this fails. A test that instead pointed
    /// `write_banlist` at some other unwritable path would pass either way,
    /// because nothing would have touched `banlist.json` in the first place.
    #[test]
    fn a_failed_write_leaves_the_previous_list_intact() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("banlist.json");
        let mut list = BanList::new(path.clone());
        list.add(&parse_ban_target("10.0.0.0/8").unwrap(), 1, 9999999999)
            .unwrap();
        let (dest, json) = list.take_pending_dump().unwrap();
        write_banlist(&dest, &json).unwrap();
        let first = std::fs::read_to_string(&path).unwrap();
        assert!(first.contains("10.0.0.0/8"));

        // Occupy the temporary path with a directory, so writing it fails
        // while `banlist.json` itself is perfectly writable.
        let tmp = path.with_extension("json.tmp");
        std::fs::create_dir(&tmp).unwrap();

        list.add(&parse_ban_target("192.168.0.0/16").unwrap(), 1, 9999999999)
            .unwrap();
        let (dest, json) = list.take_pending_dump().unwrap();
        assert!(write_banlist(&dest, &json).is_err(), "the tmp write must fail");
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            first,
            "a failed write must not touch the live banlist"
        );

        // And the failure is retryable: the caller re-arms the dirty flag, so
        // the next flush writes the list that was pending.
        list.mark_dirty();
        std::fs::remove_dir(&tmp).unwrap();
        let (dest, json) = list.take_pending_dump().expect("still dirty after a failed write");
        write_banlist(&dest, &json).unwrap();
        let after = std::fs::read_to_string(&path).unwrap();
        assert!(after.contains("10.0.0.0/8") && after.contains("192.168.0.0/16"));
        assert!(!tmp.exists(), "no temporary left behind after a successful write");
    }

    /// A ban list written with a non-canonical subnet must still be
    /// removable. `ipnet` keeps host bits on construction, so a file (or a
    /// hand edit) carrying `10.0.0.5/8` used to load under that exact key
    /// while `setban ... remove` looked up `10.0.0.0/8` — a ban nothing could
    /// lift, and a second `setban add` would insert a duplicate beside it.
    #[test]
    fn a_non_canonical_address_is_still_removable() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("banlist.json");
        std::fs::write(
            &path,
            r#"{"banned_nets": [
                {"version": 1, "address": "10.0.0.5/8", "ban_created": 1, "banned_until": 9999999999}
            ]}"#,
        )
        .unwrap();

        let (mut list, recreated, _) = BanList::load(&path);
        assert!(!recreated);
        assert_eq!(
            list.list(0).iter().map(|e| e.address.as_str()).collect::<Vec<_>>(),
            ["10.0.0.0/8"],
            "the address is canonicalised on load"
        );
        assert!(list.is_banned(&"10.1.2.3".parse().unwrap(), 100));
        list.remove(&parse_ban_target("10.0.0.0/8").unwrap())
            .expect("the ban must be removable by the name setban computes");
        assert!(!list.is_banned(&"10.1.2.3".parse().unwrap(), 100));
    }

    /// Core reads both timestamps with `getInt<int64_t>()` and answers a
    /// parse throw by discarding the *whole* file. satd's `setban` takes a
    /// `u64` bantime, so an operator could otherwise write a banlist that
    /// silently costs Core every one of its bans.
    #[test]
    fn a_saturating_bantime_stays_readable_by_core() {
        let mut list = BanList::default();
        list.add(&parse_ban_target("1.2.3.4").unwrap(), 0, u64::MAX)
            .unwrap();
        let entry = list.list(0)[0];
        assert_eq!(entry.banned_until, i64::MAX as u64);
        assert!(i64::try_from(entry.banned_until).is_ok());
    }

    /// Every mutation must leave the list dirty, so a caller that forgets to
    /// flush is a bug the type can express rather than one only a restart
    /// reveals.
    #[test]
    fn every_mutation_marks_the_list_dirty() {
        let dir = tempfile::tempdir().unwrap();
        let mut list = BanList::new(dir.path().join("banlist.json"));
        let target = parse_ban_target("10.0.0.0/8").unwrap();

        let settle = |list: &mut BanList| {
            let (dest, json) = list.take_pending_dump().expect("pending");
            write_banlist(&dest, &json).unwrap();
            assert!(!list.is_dirty());
        };

        list.add(&target, 1, 9999999999).unwrap();
        assert!(list.is_dirty(), "add");
        settle(&mut list);

        list.add(&target, 1, 9999999999).unwrap();
        assert!(!list.is_dirty(), "a ban that neither inserts nor extends changes nothing");

        list.add(&target, 1, 99999999999).unwrap();
        assert!(list.is_dirty(), "extending a ban");
        settle(&mut list);

        list.prune_expired(u64::MAX);
        assert!(list.is_dirty(), "prune_expired");
        settle(&mut list);

        list.add(&target, 1, 9999999999).unwrap();
        settle(&mut list);
        list.remove(&target).unwrap();
        assert!(list.is_dirty(), "remove");
        settle(&mut list);

        list.add(&target, 1, 9999999999).unwrap();
        settle(&mut list);
        list.clear();
        assert!(list.is_dirty(), "clear");
    }

    #[test]
    fn is_banned_by_subnet() {
        let mut list = BanList::default();
        let subnet = parse_ban_target("127.0.0.0/24").unwrap();
        list.add(&subnet, 1000, 2000).unwrap();

        let ip: IpAddr = "127.0.0.1".parse().unwrap();
        assert!(list.is_banned(&ip, 1500));
        assert!(!list.is_banned(&ip, 2500));
    }
}
