# The SDK ships the whole build: `make` packs the .s9pk, `make install`
# sideloads it to the server in ~/.startos/config.yaml. Overrides, if this
# package ever needs any, go above the include.
include node_modules/@start9labs/start-sdk/s9pk.mk
